# Generated by Django 2.1.7 on 2019-03-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texta_api', '0005_datarow_dataset_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarow',
            old_name='dataset_id',
            new_name='dataset',
        ),
    ]
