# Generated by Django 2.1.7 on 2019-03-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texta_api', '0007_remove_datarow_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='rows',
            field=models.TextField(blank=True),
        ),
    ]
